### ISSUE TITLE
how to get this goingq

### ISSUE THREAD

**Issue by fritzvd** [emkay/nesly-assembler#1]
Hi Emkay,

I was pursuing a very similar path to yours, and couldn't really find a way to contact you other than gh-issues. Anyways. I was wondering what kind of input it uses. Is it nesasm compatible assembly or a specific subset?

Anways I tried your example from the nesly repo and couldn't get that to work with this assembler. Am I missing anything?

Fritz

**Comment by emkay** [comment]
hey Fritz, yeah this isn't completely working yet. I'm using nesasm to test it out with. I've gotten close to getting it working, but haven't had a ton of time to dig down into it. If you want to take a crack I would love the help.

**Comment by fritzvd** [comment]
Actually! I forgot to add the char file. So I got it now. The error message was kind of `misleading` == `undefined`

**Comment by emkay** [comment]
@fritzvd yeah it needs a lot of love. It's a port over so I expect error messages and api to change a lot.

**Comment by fritzvd** [comment]
And thanks for responding so swiftly. I was actually starting in the process of writing some tools to aid with C compilation for cc65. But this feels like it would work will with js-devs. which was what I was aiming for. Just sort of serendipitously stumbled upon this repo :tada: 

So let me see what I can do / find time for and get back to you.

**Comment by emkay** [comment]
@fritzvd what would be cool to get going would be to have some test asm and get some tests going to see what else needs to be done. My goal for this is to use this so I don't have to depend on compiling an external dependency when working on Nintendo stuff in js. If we had this going we could just add it as a normal module to `nesly-sound` and use it in the browser.

**Comment by emkay** [comment]
@fritzvd awesome! yeah feel free to open issues, send PRs etc. thanks!

**Comment by fritzvd** [comment]
yes. also instead of pointing to obscure compilers somewhere --> just `npm install`

**Comment by fritzvd** [comment]
one more thing nesly-sprite seems like it can rip the sprite can it also _put_ back a sprite?

**Comment by emkay** [comment]
was working on a similar module [`nesly-meld`](https://github.com/emkay/nesly-meld) to do exactly that.
